// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArMU4U9jdlIOQdTX9t0BxMUCcZ_juCv3w',
    appId: '1:598736734217:web:ed9b1e162f321304da90d8',
    messagingSenderId: '598736734217',
    projectId: 'locality-b29e8',
    authDomain: 'locality-b29e8.firebaseapp.com',
    storageBucket: 'locality-b29e8.firebasestorage.app',
    measurementId: 'G-L62SM6FMCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-LKkRb3pfCJ0xiZi5UN0n7mpXGdQEjY',
    appId: '1:598736734217:android:b6557b5033518972da90d8',
    messagingSenderId: '598736734217',
    projectId: 'locality-b29e8',
    storageBucket: 'locality-b29e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHDawUMmIT2cnaH-EDkGpjMIQ8OozAg8',
    appId: '1:598736734217:ios:580533df1fd04991da90d8',
    messagingSenderId: '598736734217',
    projectId: 'locality-b29e8',
    storageBucket: 'locality-b29e8.firebasestorage.app',
    iosBundleId: 'com.example.locality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAHDawUMmIT2cnaH-EDkGpjMIQ8OozAg8',
    appId: '1:598736734217:ios:580533df1fd04991da90d8',
    messagingSenderId: '598736734217',
    projectId: 'locality-b29e8',
    storageBucket: 'locality-b29e8.firebasestorage.app',
    iosBundleId: 'com.example.locality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArMU4U9jdlIOQdTX9t0BxMUCcZ_juCv3w',
    appId: '1:598736734217:web:167d679e937c6a3fda90d8',
    messagingSenderId: '598736734217',
    projectId: 'locality-b29e8',
    authDomain: 'locality-b29e8.firebaseapp.com',
    storageBucket: 'locality-b29e8.firebasestorage.app',
    measurementId: 'G-Y472TSQSX0',
  );
}
