name: Build and Deploy Flutter App

on:
  push:
    branches:
      - master
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
      - name: Cleaning Flutter
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      - name: Get dependencies
        run: flutter pub get
      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos --release
      - name: Create DMG installer
        run: |
          npm install -g create-dmg
          create-dmg build/macos/Build/Products/Release/Runner.app build/macos/Build/Products/Release/

  release:
    needs: [build-android, build-ios, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Android APK
        uses: actions/download-artifact@v3
        with:
          name: build-android
      - name: Download iOS IPA
        uses: actions/download-artifact@v3
        with:
          name: build-ios
      - name: Download macOS DMG
        uses: actions/download-artifact@v3
        with:
          name: build-macos
      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest-release
          name: Latest Releases
          draft: false
          prerelease: false
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/ipa/Runner.ipa
            build/macos/Build/Products/Release/Runner*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}