name: Build and Deploy Flutter App

on:
  push:
    branches:
      - master
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
      - name: Cleaning Flutter
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: [build-android]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Android APK
        if: needs.build-android.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./artifacts
      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest-release
          name: Latest Releases
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}