name: Build and Deploy Flutter App

on:
  push:
    branches:
      - master 
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
      - name: Cleaning Flutter
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Delete Existing Releases (if any)
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest-release
          name: Latest Releases
          draft: false
          prerelease: false
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/Runner.app
            build/macos/Build/Products/Release/Runner.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      - name: Get dependencies
        run: flutter pub get
      - name: Build iOS (simulator, no code signing)
        run: flutter build ios --release --no-codesign

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos --release